### ISSUE TITLE
Fächer aus Grundschulsystematik EAF bzw. AGMuD-Liste als closeMatch

### ISSUE THREAD

**Issue by bokahama** [dini-ag-kim/schulfaecher#4]
In der AGMuD-Liste finden sich unter 280 nochmals eine Auswahl an Schulfächern.
Die Identifier zum jeweiligen Fach sollten ebenfalls closeMatch bei den jeweiligen Fächern werden.

**Comment by sroertgen** [comment]
Habe ich eingefügt!
