### ISSUE TITLE
Vorschläge für weitere Fächer

### ISSUE THREAD

**Issue by hfreye** [dini-ag-kim/schulfaecher#6]
Meine Sicht aus dem Rahmenlehrplan Berlin-Brandenburg 1-10 
Die GOST (gymnasiale Oberstufe = Sek. II) muss ich noch liefern.

unter "Moderne Fremdsprachen" (ein Rahmenlehrplan) wird in Berlin-Brandenburg zusätzlich angeboten:
Hebräisch
Japansich
Neugriechisch
Polnsich
Portugiesisch
Sorbisch/Wendisch

aber auch:
Astronomie (länderabhängig eingenständig (bei uns Wahlpflicht) oder in Physik integriert)
Deutsche Gebärdensprache
Gesellschaftswissenschaften (Verbindung von Geschichte, Politische Bildung und Geografie in 5./6. Klasse)
Lebensgestaltung-Ethik-Religions­kunde (überkonfessionsionell, "Ersatz" von konfessionellem Religionsunterricht)
Naturwissenschaften (Verbindung von Bio, Physik, Chemie - in 5./6. als Pflichtfach und in Sek I als Wahlpflichtfach)
Psychologie (Fach der Sek. II und Wahlpflichtfach der Sek I)
Theater als Synonym zu Darstellenden Spiel

Exoten: 
Wirtschaft-Arbeit-Technik (Sek. I, große Ähnlichkeit zu "Wirtschaft" )
Sozialwissenschaften/Wirtschaftswissenschaft (Wahlpflichtfach der Sek I.)

Gruß
Henry

**Comment by oellers** [comment]
Ergänzend zu Henrys Vorschlägen, habe ich eine [Liste der Schulfächer](https://uni-muenster.sciebo.de/apps/onlyoffice/s/TeQDtcxevXPoohK?fileId=2129969603) erstellt. Die Systematisierung ist ein zeilenweiser Abgleich der bestehenden Liste mit dem openeduhub, den Klett-Erweiterungen und dem Lehrplannavigator NRW, wobei Abweichungen _orange_ markiert sind.

**Comment by sroertgen** [comment]
Hallo zusammen,

basierend auf eurem Input würde ich folgende Fächer hinzufügen:

(von @hfreye)

- Hebräisch
- Japansich
- Neugriechisch
- Polnisch
- Portugiesisch
- Sorbisch/Wendisch

- Astronomie
- Deutsche Gebärdensprache
- Gesellschaftswissenschaften (Verbindung von Geschichte, Politische Bildung und Geografie in 5./6. Klasse)
~Lebensgestaltung-Ethik-Religions­kunde (überkonfessionsionell, "Ersatz" von konfessionellem Religionsunterricht)~ -> das würde ich mit dem bereits vorhandenem "Ethik" gleichsetzen
- Naturwissenschaften (Verbindung von Bio, Physik, Chemie - in 5./6. als Pflichtfach und in Sek I als Wahlpflichtfach): Hier würde ich Relationen zu Bio, Physik und Chemie einfügen
- Psychologie (Fach der Sek. II und Wahlpflichtfach der Sek I)
- Theater als Synonym zu Darstellenden Spiel (`skos:altLabel`)

Exoten:
- Wirtschaft-Arbeit-Technik (Sek. I, große Ähnlichkeit zu "Wirtschaft" )
- Sozialwissenschaften/Wirtschaftswissenschaft (Wahlpflichtfach der Sek I.)

Hier bin ich noch unschlüssig, wie wir mit den ganzen Varianten von Wirtschaft-... umgehen sollen. Ich stelle das nochmal in den Gruppen zur Diskussion.

Außerdem würde ich noch basierend auf @oellers Hinweis zu Klett ergänzen:

- Ernährung
- Pädagogik / Erziehungswissenschaften
- Medienbildung

Ich spreche das nochmal in den Gruppen an und bereite es dann entsprechend vor!

Vielen Dank schonmal!

**Comment by sroertgen** [comment]
Ich habe die Fächer wie hier und in der OER-Metadatengruppe (https://pad.gwdg.de/kFwdz1njS16GYKq0m6V-Xg) besprochen hinzugefügt!

Daher schließe ich das Issue.
